# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tk_slack',
                'doc_host': 'https://Datatistics.github.io',
                'git_url': 'https://github.com/Datatistics/tk_slack',
                'lib_path': 'tk_slack'},
  'syms': {'tk_slack.core': {'tk_slack.core.foo': ('core.html#foo', 'tk_slack/core.py')}}}
